version: '3'
services:
  notebook:
    image: notetaker
    env_file:
      - .env
    ports:
      - 8998:8998
    working_dir: /app
    volumes:
      -  ./src:/app
  streamlit:
    image: notetaker
    env_file:
      - .env
    ports:
      - 8501:8501
    working_dir: /app
    volumes:
      -  ./src:/app
    entrypoint: ''
    command: ["streamlit", "run", "app.py", "--server.runOnSave=true", "--browser.gatherUsageStats=false"]

  history:
    image: notetaker
    env_file:
      - .env
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./src:/app
      - sqlite_data:/app/data
    entrypoint: ''
    command: [ "uvicorn", "src.endpoints.endpoints:app", "--reload", "--host", "0.0.0.0", "--port", "8000" ]




